PRONAME:= person
TARGET:= lib$(PRONAME)
PRE_DEFINED := 
BUILD_PATH := $(shell pwd)
INCLUDES := $(BUILD_PATH)/inc \
            ../inc \
            ../body/inc \
            ../brain/inc \
            ../limbs/inc
            
LIBS_PATH := ../lib

LIBS := body brain limbs 

include ../../static.mk
